### ISSUE TITLE
Titel content UU2014

### ISSUE THREAD

**Issue by UlrikeR** [dflippo/UU2014#35]
Hi, 
I am building my site http://sciecom.de/wp/ using the UU2014 template. Thanks for a great template! 
Just have a couple of questions: 
When I fill my own title into the titel field, it will show twice in the firefox tab. Why? 
I also set the theme to showing the chalice icon in the titel, but as you can see, it is not showing it. 
I would like to have the option NOT to show anything here. Alternatively, how could I replace the chalice with, say, my own icon? 

thanks for support! Uli

**Comment by dflippo** [comment]
In WordPress there is a title for a site and a title for a specific page.  The UU2014 theme displays the site title and site description in the header banner and the page/post title is just before the content for that page/post.

In Appearance -> Customize you can hide the image near the site title in the section called "UU2014 - Display and Hide Features".

If you want to replace the title image with your own, you need to add a bit of JavaScript to a Text Widget in your footer widget area:
```
<script>
document.getElementById("site-title-image").src = "/wp-content/themes/uu-2014/images/UUA_Symbol_dark_148_200.png";
</script>
```
Here I am changing the header image to a image that is normally in the background of the footer but you can replace the image location with any image file that you have uploaded to WordPress.

**Comment by UlrikeR** [comment]
thank you!! :)

On Fri, Jan 9, 2015 at 5:24 AM, Dan Flippo <notifications@github.com> wrote:

> In WordPress there is a title for a site and a title for a specific page.
> The UU2014 theme displays the site title and site description in the header
> banner and the page/post title is just before the content for that
> page/post.
>
> In Appearance -> Customize you can hide the image near the site title in
> the section called "UU2014 - Display and Hide Features".
>
> If you want to replace the title image with your own, you need to add a
> bit of JavaScript to a Text Widget in your footer widget area:
>
> <script>
> document.getElementById("site-title-image").src = "/wp-content/themes/uu-2014/images/UUA_Symbol_dark_148_200.png";
> </script>
>
> Here I am changing the header image to a image that is normally in the
> background of the footer but you can replace the image location with any
> image file that you have uploaded to WordPress.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dflippo/UU2014/issues/35#issuecomment-69291514>.
>



-- 
Ulrike Richter
Dipl. Biologin
Fotografin
0173 900 8703
