### ISSUE TITLE
Problem using anchor link to an anchor tag on a different page

### ISSUE THREAD

**Issue by kaeelgie** [dflippo/UU2014#36]
I am trying to link from the term "over-insulate" on this page
http://www.aconwr.ca/directory-of-heritage-practitioners/roofs/
to a section mid-way down this page
http://www.aconwr.ca/directory-of-heritage-practitioners/roofs/roofs-helpful-tips/
The hyperlink goes to the second page, but it does not go to the top of the page, not the point further down. 
(I test this out on my smartphone, where the problem is very clear.)

Here is the code I have been using:
For the link: <li>Heritage roofs need to breathe - don't <a href="http://www.aconwr.ca/roofs/roofs-helpful-tips/#insulate">over-insulate</a>.</li>
for the anchor tag
<a name="insulate" id="insulate"></a>Heritage roofs need to breathe - don't over-insulate.

After trying many variations and consulting many forums, I stumbled upon this WordPress forum
https://wordpress.org/support/topic/anchor-link-to-an-anchor-tag-on-another-page-does-not-work
The solution for her problem was to try a different, default, theme.

I'm wondering if you have encountered this problem before with UU2014 (which I love)
If so, do you know a solution, or work-around?

**Comment by dflippo** [comment]
Are you using the #linkid at the end of the URL?  I use anchor links on the
tech support page on www.kentuu.org without issues.  If you look there in
the last expanding menu you will see links to the whole technical support
page and sub menu links to specific sections.  I am pretty sure it isn't
the theme.  Let me know if my example isn't clear enough.  Good luck.

**Comment by kaeelgie** [comment]
Dan,On www.kentuu.org all those technical support anchors seem to be on the same page.#Groups #OnlineMeetings # GoogleApps
What I'm wanting to do is link to a new page AND also to an anchor half-way down that page.I can link to the top of the new second page, just fine, but I can't figure out how to get down the page.I think I'm using the #linkid. This was my instruction to go to the anchor linkHeritage roofs need to breathe - don't <a href="http://www.aconwr.ca/roofs/roofs-helpful-tips/#insulate">over-insulate</a>.

The two pages I'm trying to link arehttp://www.aconwr.ca/directory-of-heritage-practitioners/roofs/
andhttp://www.aconwr.ca/directory-of-heritage-practitioners/roofs/roofs-helpful-tips/#insulate
 (I haven't worked out the menu yet, sorry) Kae Elgie

**Comment by dflippo** [comment]
The HTML is the same whether you are on the same page or a different page.  When you are on the homepage of the kent website, the following is very similar to the HTML for three of the links in the menu:
```
<a href="http://www.kentuu.org/membership/technical-support/#Groups">Mailing Lists / Google Groups</a>
<a href="http://www.kentuu.org/membership/technical-support/#OnlineMeetings">Online Meetings and Teleconferences</a>
<a href="http://www.kentuu.org/membership/technical-support/#Church20">Church 2.0 Presentations</a>
```
All three of these pages are a different page from the home page.  The fact that the target of the link is on the same site is irrelevant.  Now, in the code on the target the page, I added the following headers throughout the page with anchors:
```
<h2><a id="Groups"></a>Mailing Lists / Google Groups</h2>
<h2><a id="OnlineMeetings"></a>Online Meetings and Teleconferences</h2>
<h2><a id="Church20"></a>Church 2.0 Presentations</h2>
```
You should notice that the "#" and the "id" values of the links and anchors are identical.  You can only link to a lower section of a website's page if they have already added anchors like:
```
<a id="OnlineMeetings">
```
You will have to look at their HTML and figure out whether they have provided these anchors or not.  It will also work if the target anchor uses the "name" attribute like:
```
<a name="OnlineMeetings">
```
The theme had nothing to do with either the link or the anchor.  I manually added the link to the menu and I manually added the anchor tags to the content of the page.

**Comment by kaeelgie** [comment]
Thanks Dan, for your clear explanation.It's working exactly the way I wanted it to, now.
 Kae Elgie
