### ISSUE TITLE
child theme breaks site

### ISSUE THREAD

**Issue by IgnitionMetalArtDesign** [dflippo/UU2014#38]
Hi !
I have recently started using your great theme.......in short , it is what I have been looking for for over a year...my website has been up for 3 years or so and I have used various themes, but UU 2014 fits my needs like a glove! Excellent responsive function and wonderful colors! 

The only issue up to now is that I cannot get a child theme to work without breaking the site.
I am using the Wordpress Codex instructions     http://codex.wordpress.org/Child_Themes        to add a child theme. I have set up a child theme folder rcalled   uu-2014-child in the Themes Directory.  It has a style.css and functions.php file.

Here is the code in the child.css 

/*
 Theme Name:   uu-2014
 Description:  uu-2014-child
 Author:       Marty Slusser
 Author URI:   http://ignitionmetlartdesign.com
 Template:     uu-2014
 Version:      1.0.0
 */

Here is the code in the functions.php file
<?php
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}

Should be using the import method rather than enqueue?
Do I need to add additional .css files within the enqueue?

After I activate the child theme and reload the site, boom, all styling is gone, and I have to delete the them and reload it to restore

See anything I should do differently?

Thanks so much!

Marty

**Comment by IgnitionMetalArtDesign** [comment]
I should add that I did add       display:none       to the parent  style.css around line 1023. 
since I wanted to use a different search bar in a different location. I would prefer to use the child theme of course but at the time could not make the child theme work, so this was a work a round

I am using uu-2014 version 1.3.6 because after updating to 1.3.8 I could not take out the sidebar nav many after several hours of searching and trying different ways. So I just reverted to 1.3.6 and I am happy with it!

Thanks again
Marty

**Comment by dflippo** [comment]
Marty,

Yes, you should use enqueue and the theme has more than one.  You can see the theme's enqueue statements in lines 211 to 243 of the theme's functions.php file:
https://github.com/dflippo/UU2014/blob/master/functions.php

To test whether your code is working, I recommend temporarily enabling the original theme and disabling all plugins.  Then view you homepage and right click to view source.  Save this in a text file for later comparison to when you have the child theme enabled.  You will want to look for ".css" and ".js" files being added to the header and footer.  You want to disable all plugins because they add their own files and would make the comparison much more difficult.  Hopefully, knowing the theme's list of enqueues and then comparing the HTML output will help you quickly identify if you have a missing or broken enqueues.  I should also point out that when you have it right, the URLs to the theme's files should be exactly the same path since you are trying to enqueue the parent theme's css and js files in the parent directory folder.  You should enqueue your own style.css file from your folder after the parent theme's so your changes can override the parent style sheet.

If you are using the very latest version, I fixed a bug that prevented users from disabling the sidebar in the WP customizer.  Look in Appearance -> Customize in the "uu2014 - display and hide features" section.  It shouldn't be hard to disable and then you can run future updates too.  I also ask that you try this new version because I want to make sure that you haven't found another bug.  You might want to try the theme's new reset feature in the customizer to ensure you have a good starting point for your theme settings.

Please let me know if these suggestions help you.  I hope my suggestions are clear but if not, I might have you send me a zip of your child theme so I can see what is happening on my development instance.

Dan

**Comment by dflippo** [comment]
One more thing, I just noticed your comment about 1023.  That sounds like you are copying the entire style sheet.  You should only have your changes in your child style sheet, not everything.  BTW, if all you need are CSS changes, it is easier to just put those in a text widget in your footer widget area.

**Comment by IgnitionMetalArtDesign** [comment]
Thanks much for the quick response!



As to line 1023, what I actually did was to ADD   a line  “display:none;”
  in the  search-box selector in parent style.css….may be moot though since
the goal is to get my child theme working correctly, and adding to a parent
file isn’t the correct way anyway:)



I read your comments and suggestion in the other email and will follow
those steps, but will load 1.3.8,  instead 1.3.6 and go from there



Thank you Dan



Marty



*From:* Dan Flippo [mailto:notifications@github.com]
*Sent:* Monday, January 19, 2015 12:48 PM
*To:* dflippo/UU2014
*Cc:* Marty Slusser
*Subject:* Re: [UU2014] child theme breaks site (#38)



One more thing, I just noticed your comment about 1023. That sounds like
you are copying the entire style sheet. You should only have your changes
in your child style sheet, not everything. BTW, if all you need are CSS
changes, it is easier to just put those in a text widget in your footer
widget area.

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/38#issuecomment-70557863>.

**Comment by IgnitionMetalArtDesign** [comment]
Hello Dan



Well I have  taken steps as you outlined and still not able to get a child
theme to appear in the themes area, so of course could not activate it

Here is a link https://app.sugarsync.com/iris/wf/D6184542_94323924_867887
to a ss of the folders in filezilla, a list in word doxc of the steps
taken, the child css and php files  and a copy of the source code text I
copied after the fresh install of the them. I realize that this a fairly
technical development issue, so I am happy to enlist a paid developer if
you can recommend one familiar with uu2014 , if this request is outside the
usual scope of support.  One way or another, I want to use the theme, it
fits my needs very well and I have tried several.



Thanks much

Marty

*From:* Dan Flippo [mailto:notifications@github.com]
*Sent:* Monday, January 19, 2015 12:35 PM
*To:* dflippo/UU2014
*Cc:* Marty Slusser
*Subject:* Re: [UU2014] child theme breaks site (#38)



Marty,

Yes, you should use enqueue and the theme has more than one. You can see
the theme's enqueue statements in lines 211 to 243 of the theme's
functions.php file:
https://github.com/dflippo/UU2014/blob/master/functions.php

To test whether your code is working, I recommend temporarily enabling the
original theme and disabling all plugins. Then view you homepage and right
click to view source. Save this in a text file for later comparison to when
you have the child theme enabled. You will want to look for ".css" and
".js" files being added to the header and footer. You want to disable all
plugins because they add their own files and would make the comparison much
more difficult. Hopefully, knowing the theme's list of enqueues and then
comparing the HTML output will help you quickly identify if you have a
missing or broken enqueues. I should also point out that when you have it
right, the URLs to the theme's files should be exactly the same path since
you are trying to enqueue the parent theme's css and js files in the parent
directory folder. You should enqueue your own style.css file from your
folder after the parent theme's so your changes can override the parent
style sheet.

If you are using the very latest version, I fixed a bug that prevented
users from disabling the sidebar in the WP customizer. Look in Appearance
-> Customize in the "uu2014 - display and hide features" section. It
shouldn't be hard to disable and then you can run future updates too. I
also ask that you try this new version because I want to make sure that you
haven't found another bug. You might want to try the theme's new reset
feature in the customizer to ensure you have a good starting point for your
theme settings.

Please let me know if these suggestions help you. I hope my suggestions are
clear but if not, I might have you send me a zip of your child theme so I
can see what is happening on my development instance.

Dan

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/38#issuecomment-70556285>.

**Comment by IgnitionMetalArtDesign** [comment]
Hi Dan
I am thinking maybe I don't need a child theme (tho I am used to working with one  from habit and would prefer to use one) ,  if there is another way to customize the theme  

   The enque child theme method VS the old way,  "import" is throwing me off the trail to resolution...and each theme has it's own unique needs for a child theme and I am really trying to get a grasp on enque:)
 
Can you show me a way to keep the Primary Sidebar active BUT apply "display:none" to the secondary menu that resides in the Primary Sidebar ?  Maybe this can be done with a linking script in the footer? Custom.css file? dunno,  just grasping:)

I want to keep  the Primary Sidebar area for other things, but I do not need a secondary menu to appear there......the main menu will suffice nicely.........so far from researching it looks like the only way to NOT  have the secondary menu is to NOT have the Primary Sidebar either....

Thanks
marty

**Comment by IgnitionMetalArtDesign** [comment]
I think I found a way to keep Primary Sidebar active BUT remove the display of the  secondary menu_ that resides in the Primary Sidebar  (same effect as "display:none")

Here is the solution I am testing, is working so far

I just created a blank menu (a new menu with no items in it) and assigned that to the second menu. It then disappeared. No plugins or CSS changes required.
This is on wp_nav_menu() codex page
3.5.0: If a menu has no items, don't output any markup.
Here is the source
http://core.trac.wordpress.org/browser/tags/3.6.1/wp-includes/nav-menu-template.php#L180

SIMPLE! 

I would still like to install a working child theme so hopefully you can help with that....my problem with the child theme seems to be in the enques syntax......hope to hear more on that subject when you have time

Love the theme, and I am very determined to iron out what I need to for my application....

Thanks Dan,
Marty

**Comment by dflippo** [comment]
Marty, it is funny because I responded to two other people with exactly your solution before seeing your post.  It was a busy week but I plan to create a sample child theme over the next couple weeks.  I will probably create a second project here on Github and will respond to this thread when it is ready.

**Comment by IgnitionMetalArtDesign** [comment]
Sounds good....meanwhile I will immerse my self in learning to write scripts to put in the footer / as text
Had no idea that was an option until I came here!:)
Thanks much
Marty

**Comment by dflippo** [comment]
Marty,

I have published an example child theme at https://github.com/dflippo/uu2014-child
You can download the zip from:
https://github.com/dflippo/uu2014-child/archive/master.zip

I tested it on my own development server and it worked without any issues using the enqueue method for syles and JavaScript.  Let me know if you have any problems.

Dan

**Comment by IgnitionMetalArtDesign** [comment]
Thanks so much Dan………..GREATLY appreciated!

Marty



*From:* Dan Flippo [mailto:notifications@github.com]
*Sent:* Wednesday, February 04, 2015 2:53 PM
*To:* dflippo/UU2014
*Cc:* Marty Slusser
*Subject:* Re: [UU2014] child theme breaks site (#38)



Marty,

I have published an example child theme at
https://github.com/dflippo/uu2014-child
You can download the zip from:
https://github.com/dflippo/uu2014-child/archive/master.zip

I tested it on my own development server and it worked without any issues
using the enqueue method for syles and JavaScript. Let me know if you have
any problems.

Dan

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/38#issuecomment-72957970>.
