### ISSUE TITLE
Can't figure out how to hide "Recent Posts, Archives, Categories" on side menu

### ISSUE THREAD

**Issue by kaeelgie** [dflippo/UU2014#39]
Thank you for uploading the new release version 1.3.8 to WordPress.  It hid the Author, Date, Categories, etc of my posts, just what I wanted.

But now I have a new problem.
Now the following categories appear below the Menu in the sidebar of our website. www.aconwr.ca
Recent Posts
Archives
Categories.
They weren't there before. 

Perhaps I hid them before, but I can't find a place to do this now.
I do want a side menu to display, but not those "things" (whatever they are properly called) below.

**Comment by dflippo** [comment]
I responded in the other issue how to hide the sidebar and default navigation menu but let me know if you still have questions.
