### ISSUE TITLE
footer height increases sharply on certain monitor sizes 

### ISSUE THREAD

**Issue by IgnitionMetalArtDesign** [dflippo/UU2014#42]
Dan I know you are super busy, but if you have a "simple" fix please guide me on this....the footer area (all black) stretches Very high when viewed on a 1280X1024 , 1920X1080 , 1920X1200, 1680X1050, or 720X1280 monitor. If there is not a simple fix I understand but would like to eventually wrestle this one too

This vertical mega stretch occurs whether or not I have added any text/script to the footer widget area...I tested both ways

I first noticed it on my shop monitor 1920X1080.....then tested on a screen size web site tester   http://www.rapidtables.com/web/tools/screen-resolution-tester.htm 

I know that it is pretty darn hard to make a site "perfect" for all viewports....in fact my "target monitor" has always been 1366X738 since that size monitor accounts for the most common...but I would like to seamlessly cover as many monitor sizes as possible...and of course tablets and cell phones

Hope your Scouting event goes well

Thanks
 Marty

**Comment by dflippo** [comment]
If a page doesn't have enough content, the bottom footer will start sooner.  Is that what you mean?  I do have some CSS that ensures the primary content area doesn't get extremely small:
```
.site-content { min-height: 450px; }
```
You might want to try increasing this value in your child theme or a footer widget area surrounded by <style></style>
