### ISSUE TITLE
image multiple sizes

### ISSUE THREAD

**Issue by IgnitionMetalArtDesign** [dflippo/UU2014#43]
Hi Dan
I have set my WP media settings to media sizes to upload     00,00,00 (thumbnail,medium,large) to prevent  creation of multiple  image files sizes...and the intent is to upload ONLY the image size I set up 
before uploading...........99.999% of the images I upload are "thumbnails" with a max height of 100 PX and max width AUTO

Yet when I upload a single  image, multiple images are created in my uploads directory...so I am on the hunt to find the cause......and  I thought possibly the theme settings are causing the multiple sizes?

Is there anything in the theme that would be over riding this WP setting?

Just trying to eliminate the usual suspects for cause of multiple image size 

Thanks for any light you can shed

Marty

**Comment by dflippo** [comment]
Nope, I don't set that in the theme.  Some themes do because they use thumbnails for featured posts features but the theme doesn't have anything like that now.
