### ISSUE TITLE
Css

### ISSUE THREAD

**Issue by Willowcase** [dflippo/UU2014#44]
Hi Dan,
When you have some time (that is hard I know), could you help me with some css. I have changed a few things in my child theme to override parent. However, some things just don't change no matter what I do. My main thing I would like to do is remove the hover black background and white border from only the body links. Just want a plain color link in the body. No matter what, I can't get it to change, so I must not be using the proper terms to style or order or what. 
The sidebar links on hover keep the black link when the hover puts the black background and you just have a black box. Shouldn't the link color change so you can still see what you hovered over? (I see that on yours and others)
Also, some changes I made in the child theme that were working, stopped after the theme update. I had changed the color of the dotted outline for the main nav hover and now it is back to original. The changed link colors are still working but not the hover outline color. 
Could you lay me out all link styling sets, so I can see what I am doing wrong where, what terms for what to use and get me to where I can rework them in my child theme? Links should be easy to style, but I can't seem to get them all the way I want. I feel kinda stupid.

**Comment by dflippo** [comment]
First I would check out the child theme template I created here on Github and try putting your CSS in there.  That will ensure that your child CSS runs after the parent theme CSS.  Next you will want to identify the selectors in the parent theme's style.css file and try using exactly the same selectors with your updated CSS.  It can be tempting to use a different selector for the same object but that will cause you trouble.  For example, some dom objects have both class selectors (.classname) and id selectors (#id).  I mostly use class selectors in my CSS but there are a few places where I needed to use id selectors.  You should mirror whatever I used.  By using the same selectors in later CSS, you should be able to change any part of the CSS.  You should also watch out for CSS that is set in by the customizer settings.  That CSS is dynamically created by the /inc/customizer.php file and inserted inline directly in the page header.

Regarding the updates, with each release I do change some CSS and it is possible that you need to use a different selector now.  GitHub can help show you the history of the changes I made in each release to the style.css file.

It is hard to list out all the "link styling sets" without pointing you to the style.css file itself.  I've never counted but the theme probably has over 100 different selectors in there.

Regarding hover CSS, you want to search for "hover" in the parent CSS.  The most likely culprits to change are the following:
```
a:hover, a:focus, a:active {
	color: white;
	background: #333;
	text-decoration: underline;
	outline: red thin dotted;
}

.widget-area ul a:hover:before,
.widget-area ul a:focus:before {
	color: white;
	background: #333;
}

.widget-area ul a:focus,
.widget-area ul a:hover {
	color: white;
}
```

**Comment by Willowcase** [comment]
Those are the ones I used in my css. But, it will probably work right with the enqueue method. I just thought I might have overlooked a set. Thank you.
