### ISSUE TITLE
how to remove the words "Comments Off" ?

### ISSUE THREAD

**Issue by IgnitionMetalArtDesign** [dflippo/UU2014#46]
I have tried all afternoon to find a fix  with no luck......but I would like to NOT have the words "Comments Off" appear in the content area  The words appear on my Search Page after entering a search term from any page.   I do use the plugin WP Ultimate Search but  can't see any connection. After inspecting I see there is a span with that text....have looked high and low in several php files including comments.php
I have attached two snapshots of the text on the page and the spanned text in while inspecting. I use the site only as a webpage not a blog. Any direction on where to look?
Thanks!
Marty       www.ignitionmetalartdesign.com 

![2015-02-22_16-38-05](https://cloud.githubusercontent.com/assets/10599397/6321430/710c1d86-bab1-11e4-8600-c179e2113185.jpg)
![2015-02-22_16-23-13](https://cloud.githubusercontent.com/assets/10599397/6321431/710ce04a-bab1-11e4-83b5-8a2ca46727a2.jpg)

**Comment by dflippo** [comment]
That text is added by WordPress core.  However, if you want to never display comments, that is an option in the WordPress customizer in the section where you show or hide features.  The "Comments Off" statement will not appear if you have comments hidden site-wide.  I would prefer that the theme had the comments and this statement hidden by default but WordPress.org has a rule that requires comments to be initially visible.

**Comment by IgnitionMetalArtDesign** [comment]
Thanks Dan!….understood

Marty



*From:* Dan Flippo [mailto:notifications@github.com]
*Sent:* Wednesday, February 25, 2015 2:48 PM
*To:* dflippo/UU2014
*Cc:* Marty Slusser
*Subject:* Re: [UU2014] how to remove the words "Comments Off" ? (#46)



That text is added by WordPress core. However, if you want to never display
comments, that is an option in the WordPress customizer in the section
where you show or hide features. The "Comments Off" statement will not
appear if you have comments hidden site-wide. I would prefer that the theme
had the comments and this statement hidden by default but WordPress.org has
a rule that requires comments to be initially visible.

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/46#issuecomment-76078077>.
