### ISSUE TITLE
Floating Side Bar

### ISSUE THREAD

**Issue by dzamelt** [dflippo/UU2014#47]
Hi, awesome theme with loads of capability and potential!! Many thanks.

I note there is an option to include/exclude the primary sidebar from individual posts/pages but see no option to do the same with the floating sidebar. It seems that it always features when enabled, or am I missing something... I'd like it for some posts/pages but not all. Is this possible?

I'd also like to customize the footer a bit more, add a list of links and images etc, is this possible... I suspect I'll need to get more familiar with the editor etc.

Kind regards

**Comment by dflippo** [comment]
The theme by itself can't do what you are requesting but there is a way to do this with a plugin.  If you use the Jetpack plugin, it has a module called "Widget Visibility".  The sidebar is designed to disappear if you do not have any widgets and that Jetpack feature could be used to hide your widgets depending on which page is being viewed.

Like the floating sidebar, the page footer has a widget area and allows you to add any widget you like.  Widgets are provided by plugins and widget areas are provided by themes.  There are several plugins that can add the features you mention to the footer.

**Comment by dzamelt** [comment]
Thank you very much for this useful information Sir. God bless.
