### ISSUE TITLE
archive and category

### ISSUE THREAD

**Issue by hdvtwin** [dflippo/UU2014#48]
I am making a static non-blog website and have disabled comments and posts and taken archives and categories out of the widgets nav menu area. 
 I am still getting an archive and category grayed out link in the left nav bar. 
 how do I get rid of these links in the left nav menu?
http://www.ellis4fremont.com/fremont2015/
Thank you for your assistance,
Karen Harris

**Comment by dflippo** [comment]
If you don't have any widgets in the left sidebar, the theme will display some default content.  You can avoid this by adding an empty text widget to the area.  If you want to hide the left navigation menu, you should create an empty menu and then assign the empty menu to the sidebar navigation (you see this relationship in Menus in the second tab).

Alternately, if you don't want the sidebar to appear at all and want content to fill the entire width, you can do that by hiding the sidebar in the Display and Hide Features section of the Customizer.  Good luck.
