### ISSUE TITLE
Hiding the Search Widget that overlaps the header image

### ISSUE THREAD

**Issue by ltjost** [dflippo/UU2014#51]
Can you indicate how I can remove the search widget that overlays the header image?

**Comment by IgnitionMetalArtDesign** [comment]
I used the following code in my child theme to do hide the search bar. The
first line is just a comment and is not actually code.



/*THIS IS TO REMOVE SEARCH BAR FROM UPPER RIGHT CORNER*/

.search-box{

display:none}





Marty



*From:* ltjost [mailto:notifications@github.com]
*Sent:* Tuesday, March 17, 2015 8:28 AM
*To:* dflippo/UU2014
*Subject:* [UU2014] Hiding the Search Widget that overlaps the header image
(#51)



Can you indicate how I can remove the search widget that overlays the
header image?

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/51>.

**Comment by ltjost** [comment]
Thank you!  Worked great!
