### ISSUE TITLE
correct place to add custom css in child theme

### ISSUE THREAD

**Issue by IgnitionMetalArtDesign** [dflippo/UU2014#54]
Hi Dan

In the function.js file within the Child Themes folder the notation says

/**
Theme users:
Below is where you should add any custom CSS that you would like applied to your site.
This CSS is applied after the CSS from the parent theme.  
You should look at the style.css from the parent theme and use the same CSS selectors with your modifications.
*/

I have been instead using the style.css file within the Child Themes folder...and went to change a padding parameter for images that used to work nicely but now if I increase the border px, as an example,  it has no effect.      SO, ha ha  I am now wondering if after you created the child theme (THANK YOU !) I have been mis placing my CSS mods to the wrong file?

    Here is the  code I used to use in my Child Theme style.css file , before I started with UU2014, and simply copied over to the Child style.css file in the UU2014 child them, but as I said it does not seem to work anymore

.page-id-6827 .entry-content img {
  border: 5px solid #6A8999;
  font-size: 0;

Also...since there is no page id selector type of  CSS (that I know of at least) in the UU 2014  parent CSS page  I am now wondering what the syntax/selectors would be to accomplish the css mod in the child theme? And would it go into the child style.css or child function.js ?

Thanks!!
Marty

**Comment by dflippo** [comment]
You have found a typo.  CSS should go in the style.css and Javascript should go in function.js.  I'll update the message.  The style.css file in the child should override the CSS for the parent but it is very important to use EXACTLY the same selectors.  That includes whether a selector is within the block that selects based on resolution.

**Comment by IgnitionMetalArtDesign** [comment]
The waters are more clear now



Thanks Dan!



Marty



*From:* Dan Flippo [mailto:notifications@github.com]
*Sent:* Thursday, April 02, 2015 5:06 PM
*To:* dflippo/UU2014
*Cc:* Marty Slusser
*Subject:* Re: [UU2014] correct place to add custom css in child theme (#54)



You have found a typo. CSS should go in the style.css and Javascript should
go in function.js. I'll update the message. The style.css file in the child
should override the CSS for the parent but it is very important to use
EXACTLY the same selectors. That includes whether a selector is within the
block that selects based on resolution.

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/54#issuecomment-89087041>.
