### ISSUE TITLE
Where to translate 'Primary Menu'

### ISSUE THREAD

**Issue by hades7** [dflippo/UU2014#56]
Hello

I'm trying to translate 'Primary Menu' to 'Hauptmenü' (german). Where to translate this string?
Thank you.

Best regards
hades7

**Comment by dflippo** [comment]
Hades, you have found a mistake.  I need to update the uu2014.pot file to catch this and maybe a few other newer strings.  I will update the file tomorrow and I will also use an online automated translator to generate a .po and .mo file in German.  This will simplify the effort for you.  In the languages folder you use .po and .mo files to allow WordPress to automatically display translated text.  I unfortunately know very little German but I am happy to work with you.  I will send you an update when the files are ready.  Then, if you are willing, you can double-check the translations and send me updates.  If you prefer, I have a sister-in-law who has three Masters degrees and a PhD in foreign languages including German who can do this for me instead.  Until then, I recommend reviewing this page which describes the translation process:
https://developer.wordpress.org/themes/functionality/localization/

I use Poedit to create the uu2014.pot file and I can use it to create .po and .mo files for translations.  Thanks, for bringing this to my attention.  Alles gute

**Comment by hades7** [comment]
Hello dfilippo
Thank you for your fast reply. Of course I will check your translations.

Best regards
hades7

**Comment by dflippo** [comment]
Hades7,

I have uploaded the updated .pot file and provided .po files for US English and German:
https://github.com/dflippo/UU2014/tree/master/languages

You can upload these files into your "languages" folder to test if they work.  I think the easiest way to correct any of the translations is for you to edit the de.po file directly in the free version of Poedit:
http://poedit.net/ 

You can then email this file to me at dan.flippo@kentuu.org and I will add it to Github and submit a deployment to the WordPress.org repository.  That will allow other Germans to benefit from your work.

Vielen Dank!

Dan

**Comment by hades7** [comment]
Hello Dan

I've sent you the corrected translations by email.

Best regards
Flo (hades7)

**Comment by dflippo** [comment]
Flo,

I figured out what I had done wrong.  I had named the files incorrectly.  I updated the file names on GitHub and I've confirmed that they work in my test environment when I switch the language to German.  For now you can upload these files to your language folder and I will include them in my next deployment to WordPress.org.

Dan

**Comment by hades7** [comment]
Hello Dan


Perfect, thank you very much!



Best regards

Flo





Von: Dan Flippo
Gesendet: ‎Samstag‎, ‎11‎. ‎April‎ ‎2015 ‎07‎:‎16
An: dflippo/UU2014
Cc: hades7





Flo,

I figured out what I had done wrong. I had named the files incorrectly. I updated the file names on GitHub and I've confirmed that they work in my test environment when I switch the language to German. For now you can upload these files to your language folder and I will include them in my next deployment to WordPress.org.

Dan
