### ISSUE TITLE
Removing Page Titles

### ISSUE THREAD

**Issue by jelliott3** [dflippo/UU2014#58]
Hi Dan,

Quick question:  How can I delete the page name that appears at the top of the content area on each page (eg, "Home") and reduce the spacing/padding at the top?

I am embedding a simple html page in the content area, and need to have less space above it. 

Thanks.  The template is great!

Julian

**Comment by dflippo** [comment]
The theme doesn't have a feature to turn off all titles but WordPress will
allow you to remove the title from a page.  Is this for just one page?  It
sounds like a good feature for me to add as a page template.  Now the only
template besides the default allows you to create a page without a sidebar.

**Comment by jelliott3** [comment]
Hi Dan,

 

Yes, it would be a nice feature.  I definitely need to remove from one page; others might want to eliminate altogether.

 

I can modify the stylesheet or page info if I know where to look.

 

I do like the option to have one sidebar or full width. 

 

Julian

**Comment by dflippo** [comment]
I have just committed changes that include this feature as a page template:
https://github.com/dflippo/UU2014/commit/4ca802a7d8d28d0a6382a3161d9e8cbb02940e2e

I recommend downloading the zip from GitHub and manually placing the three files modified in your copy of uu-2014.  I will be deploying a theme update shortly and this change will be included.
