### ISSUE TITLE
How to remove links to next and previous article?

### ISSUE THREAD

**Issue by hades7** [dflippo/UU2014#59]
In articles, between the content of the article and the comments are links to the previous and the next article with red arrows. How to remove those 2 links?

Thank you.

**Comment by dflippo** [comment]
Put this in a text widget:
```
<style>
.nav-previous a:before { display: none; }
.nav-next a:after { display: none; }
</style>
```

**Comment by hades7** [comment]
Hello Dan


The two arrows are now hidden, but the names of the previous and the next article are still displayed. How to hide also the names of these articles?


Thank you very much for your help!



Best regards

Flo






Von: Dan Flippo
Gesendet: ‎Samstag‎, ‎11‎. ‎April‎ ‎2015 ‎06‎:‎13
An: dflippo/UU2014
Cc: hades7





Put this in a text widget:
<style>
.nav-previous a:before { display: none; }
.nav-next a:after { display: none; }
</style>
