### ISSUE TITLE
How to disable search box in the header. thank you

### ISSUE THREAD

**Issue by hcm4dp** [dflippo/UU2014#63]
Hi, 

I use your theme and I need some help please to disable research box from the header.
I know you've already answered this request, but I didn't found it.
thank you so much.
bests

**Comment by rhinmass** [comment]
I'm not sure if there is an easier way, but I added this to style.css :

/*THIS IS TO REMOVE SEARCH BAR FROM UPPER RIGHT CORNER */
.search-box {display:none}
