### ISSUE TITLE
Footer align

### ISSUE THREAD

**Issue by dzamelt** [dflippo/UU2014#65]
Just a long shot but I've recently noticed a gap beneath the footer of my blog UU theme, I'm not sure what I've done. Does anyone have any idea, suggestions or quick fixes?

I've not edited any php files recently - I've used some basic alignment script here and there to centre facebook posts, am not always 100% where to insert the script, usually directly in front of the post in question, sometimes within in it, but I'm doubtful this is the problem.

I've not yet sussed out how to set up the child theme, so I am going to attempt a restore from an earlier date. www.interfaithveganalliance.org - thanks

**Comment by dflippo** [comment]
Could what you are seeing be related to your pages being shorter than the
height of your web browser?  Try adding some things to your sidebar widget
area to see if it goes away.

**Comment by dzamelt** [comment]
Hi Dan Cheers, I did a directory restore which has seemed to do the trick, not sure what the glitch was.
