### ISSUE TITLE
Mobile menu - is there a way to collapse and expand

### ISSUE THREAD

**Issue by rhinmass** [dflippo/UU2014#66]
Hi Dan,

Is there a way to make the mobile menu expand and collapse?  We have a very deep menu structure, so it's a little overwhelming on a mobile device to see the entire menu completely expanded.  It would be great if only the top level were initially visible and each item could be individually expanded.

Here is my sandbox site:

http://uubelmont.org/fcbwp4/wordpress

Robin

**Comment by dflippo** [comment]
I understand your concern.  Unfortunately there is a necessary balance of usability and functionality for mobile menus.  Previously the theme did have menus that expanded and contracted but different mobile browsers and mobile devices would have very inconsistent results.  In many situations, it was nearly impossible for someone to select a sub-menu without navigating to the sub-menu's target.  I also did some research with normal non-technical users and they found the menu too difficult to use/read using both iOS and Android.  I will keep your request in mind and may be able to come up with a solution but for now the simpler menu seems to be more popular with most websites.  I will leave this issue open and I welcome other people's input as well.
