### ISSUE TITLE
Question about building a responsive site

### ISSUE THREAD

**Issue by rhinmass** [dflippo/UU2014#67]
Hi Dan,

Is there a way to explictly define different layouts for different device widths.

For example, I would really like to display the 3 images side by side on a wide screen, but as a slider on a phone.

Here is my sandbox site:
http://uubelmont.org/fcbwp4/wordpress

Thank you for the theme.  It's very nice.

Robin

**Comment by dflippo** [comment]
Robin,

Sorry for not getting back with you sooner.  The UU2014 theme does have 3 different layouts for different device widths and that is how it moves the sidebar down on smaller devices.  If your question is about content appearing and disappearing, it is a conscience design decision that the exact same content is available through the "computer", "tablet", and "smart phone" widths.  There is one exception and that is the menu in the sidebar which does not appear in the "smart phone" width.  Typically that menu is set to be the same as the top menu on a site and removing it makes the mobile experience better.

What you are asking for with the images is related to the HTML and CSS you put in your post or page, and not related to the theme.  You could use similar cascading style sheet techniques as the theme does to display and hide sections.  An example would look like:

```
<style>
.display-desktop { display: block; }
.display-mobile { display: none; }
@media screen and (max-width: 782px) {
.display-desktop { display: none; }
.display-mobile { display: block; }
}
</style>
<div class="display-desktop">Content that will appear only on desktop</div>
<div class="display-mobile">Content that will appear only on mobile</div>
```

You can put the CSS above directly into your post/page to get the effect you want.  You can also tweak the max-width pixels to control which devices receive which content.  However, to make this easier for people in the future, I will add this CSS to the theme the next time I do a release.  That would allow people to just add the "display-mobile" or "display-desktop" class when writing their HTML in a post or page.
