### ISSUE TITLE
Table with no borders

### ISSUE THREAD

**Issue by rhinmass** [dflippo/UU2014#68]
Hi,

I have tried every way I can think of to try to get rid of the borders on my table.

http://uubelmont.org/fcbwp4/wordpress/test

I have tried 
border=0
border:none
border-collapse:collapse
etc.

Nothing seems to make it go away.

Same table outside of wordpress, using straight html works as expected. I've tried inspecting the css in firebug but can't find what is controlling the showing of the border.

Is there a way to have a table in the UU2014 with no borders?

Thanks for any help.

Robin

**Comment by IgnitionMetalArtDesign** [comment]
Not to hijack but just a thought

Maybe change the border color to match the background?

Marty



*From:* rhinmass [mailto:notifications@github.com]
*Sent:* Friday, May 22, 2015 5:53 AM
*To:* dflippo/UU2014
*Subject:* [UU2014] Table with no borders (#68)



Hi,

I have tried every way I can think of to try to get rid of the borders on
my table.

http://uubelmont.org/fcbwp4/wordpress/test

I have tried
border=0
border:none
border-collapse:collapse
etc.

Nothing seems to make it go away.

Same table outside of wordpress, using straight html works as expected.
I've tried inspecting the css in firebug but can't find what is controlling
the showing of the border.

Is there a way to have a table in the UU2014 with no borders?

Thanks for any help.

Robin

—
Reply to this email directly or view it on GitHub
<https://github.com/dflippo/UU2014/issues/68>.

**Comment by dranet** [comment]
Did this ever get resolved? Because I'm having the same problem.

**Comment by rhinmass** [comment]
No I didn't.  I went to a different theme - 2015 Responsive, but it had the same darn problem.

**Comment by dflippo** [comment]
All,
To over-ride CSS you need to use the same CSS selector or a more specific CSS selector.  The CSS that displays borders in tables looks like this:

```
.site-main table td {
    padding: 7px 10px;
    border: 1px solid #cfcfcf;
}
```

The best way to hide the borders on one table is:

```
<style>
.site-main table.no-border td {
    border: none;
}
</style>
<table class="no-border">....</table>
```

If you are trying to remove the border from all tables, I am guessing you must be trying to use tables for layout, not as tables.  This is very bad for a number of reasons including breaking both responsiveness and accessibility for people using screen readers.  I strongly discourage you from using tables for anything other than tables of text that have headers, columns, and rows.  For layout you should use a tag like DIV.  I encourage you to read more about the issues with tables as layout at these sites:
http://www.vanseodesign.com/css/css-divs-vs-tables/
http://webdesign.about.com/od/layout/a/aa111102a.htm

**Comment by dranet** [comment]
Why can I not control tables on each page? Some tables I want borders, others I don't. Is it all or nothing with this theme?

**Comment by dflippo** [comment]
By design, tables always have borders because HTML tables should only be used for tabular data.  Tables without borders make it more difficult to see the row/column for data.  If you are using TABLE tags for layout on pages, you should be using DIV tags.  There is a free WordPress plugin, "Page Builder by SiteOrigin", that you might want to try to visually layout your pages with multiple columns/rows using DIV.
