### ISSUE TITLE
Using our own image next to the title

### ISSUE THREAD

**Issue by bfkmeyers** [dflippo/UU2014#70]
We would like to use our own image next to the title in the header and footer.  We tried using the directions at: http://uuwp.org/2015/01/08/use-image-next-title-uu2014-theme/ 
Here is the text that we put in the text widget between the script tags:

 document.getElementById("site-title-image").src = "/wp-content/uploads/2015/06/06/UUA_EQUUAL_ACCESS_logo.png"; 

The file name is correct, but I'm not positive about the directory structure.
When we choose to display the image in the header and footer, the UUA logo image is displayed.
Is there something else that we should be doing to display the images properly?

**Comment by dflippo** [comment]
It sounds like you are using the right code.  To trouble-shoot, could you test whether your image comes up correctly at 

```
http://www.your-site.org/wp-content/uploads/2015/06/06/UUA_EQUUAL_ACCESS_logo.png
```

If you do see the image in your browser, you can put the exact same URL (with the http://) in your JavaScript.  If you don't see the image, then your URL for the image is incorrect.  If you view the image in the Media library, you can right click on the image and "Open image in new tab".  Then you should see the correct URL in the address bar of your web browser.
