### ISSUE TITLE
Disappearing Customized Headers

### ISSUE THREAD

**Issue by bfkmeyers** [dflippo/UU2014#71]
We created some new header images of the correct size (1200 x 200) and uploaded them in the header image dialog.  We selected "Randomizing uploaded headers."  However, when we look at a preview of our page, no header image is shown.  When we try to change it to a specific header image, not image is shown.  Can you help us figure out what is happening here?

**Comment by dflippo** [comment]
Do you have any widgets in your header widget area?  If you add any widgets to that area, they are displayed instead of the header images.
