### ISSUE TITLE
changelog of updates?

### ISSUE THREAD

**Issue by pigsound** [dflippo/UU2014#72]
is there a changelog somewhere of your theme  from 1.3.8 to 1.3.9 and 1.3.10?
the last time i updated from 1.3.7 to 1.3.7 my css changed i made in a child theme were overriden because the new version had some changes in the css. you may understand that i would know before if something like that is to be expected with the current version again.

**Comment by dflippo** [comment]
Sorry, I have added the change log and recent WordPress.org changes to Github now.  You can see it under Releases.
