### ISSUE TITLE
Theme looks different on each browser

### ISSUE THREAD

**Issue by inmercyrejoice** [dflippo/UU2014#73]
This theme font sizes and colors on Google Chrome are different than on IE. Please help. Thank you! Also, how can I adjust the text size in the text on the widget field? Google fonts only allow me to adjust the titles and the body font text. 

this is my site: http://www.nancyjeanwalker.net/

If you look at it on Google and on IE, you will see what I mean.

**Comment by inmercyrejoice** [comment]
also is there a way to change the pointer colors for the menu on the widget area? By the way, I really like this theme. I've tried dozens. This theme is perfect for my purposes. Again, thank you.

**Comment by dflippo** [comment]
I don't have different CSS for different web browsers and fonts are consistently specified with CSS like:

```
font-size: 10px; font-size: 1.0rem;
```

This means to use a relative size from the root element (rem) and fall back on using px if the browser doesn't support the CSS3 rem approach.  Unfortunately different web browsers, versions of the same browser, and different operating systems display fonts at different scales.  There are debates about what the best CSS is for fonts but I think this article does a good job explaining why I use my approach.  It isn't perfect but about the best possible without trying to set different fonts for different browser versions.
http://snook.ca/archives/html_and_css/font-size-with-rem

In the WordPress Customizer you can tweak the font sizes throughout the theme and you might be able to use that to find a size that is "good enough" on both browsers.

The main CSS that controls how things are displayed when you mouse hovers is:

```
a:hover, a:focus, a:active {
    color: white;
    background: #333;
    text-decoration: underline;
    outline: red thin dotted;
}
```

You should add a text widget with different options to change the colors.  There are a few other places where I customize hovers and you can find them in the syle.css by looking for ":hover".
