### ISSUE TITLE
Changing Comment Text

### ISSUE THREAD

**Issue by inmercyrejoice** [dflippo/UU2014#75]
Hi, I have posted a few times, but I'm guessing you are busy. I've managed to resolve every issue except one. I want to change the comment text. It reads "would enjoy hearing your thoughts"; but my site is about human trafficking awareness, so the word "enjoy" is inappropriate. I would like to write "Please share your thoughts."

I've tried everything I can to resolve this but there is nowhere on Wordpress or in your theme that give me this option.

Other than that, I want to thank you for beautifully designed theme. It's the only Wordpress theme that fits my needs.

**Comment by dflippo** [comment]
For anyone seeing this question, the response was provided on WordPress.org:
https://wordpress.org/support/topic/cannot-change-comment-text?replies=6#post-7169341
