### ISSUE TITLE
Disable Secondary menu in left sidebar

### ISSUE THREAD

**Issue by martinbeall** [dflippo/UU2014#78]
I cannot disable the Secondary menu in left sidebar. 
Is there a way to do this? Currently I have it set to -Select- and do not wish to display a menu here.
Many thanks for a great theme!

**Comment by hdvtwin** [comment]
I have the same issue, was it solved??

**Comment by dflippo** [comment]
The easiest way is to create an empty menu and assign it to the secondary menu.  I do plan to create a specific setting to disable the sidebar menu.

**Comment by hdvtwin** [comment]
Thanks you so much I did find the answer and made the empty menu.  I am totally recreating the site in the latest version.
