### ISSUE TITLE
New site using UU2014 theme launched

### ISSUE THREAD

**Issue by SScott-UUCC** [dflippo/UU2014#84]
The UU Church of Columbia, Missouri has just launched its redesigned website using the UU2014 theme. We thought you might want to add it to your list of UU churches using the theme.

You'll find the site at http://uuchurch.net.

**Comment by IgnitionMetalArtDesign** [comment]
NICE site! I use the same UU 2014 platform, tho not for a church

Yours is easy to navigate and user friendly

Good job!

Marty

[image: new square logoA]

Marty Slusser

Ignition Metal Art Design

909 660 0913

See My Artwork at

www.ignitionmetalartdesign.com

and visit my Facebook Page [image: facebook]

www.facebook.com/IgnitionMetalArtDesign

_From:_ SScott-UUCC [mailto:notifications@github.com]
_Sent:_ Monday, October 05, 2015 3:20 PM
_To:_ dflippo/UU2014 UU2014@noreply.github.com
_Subject:_ [UU2014] New site using UU2014 theme launched (#84)

The UU Church of Columbia, Missouri has just launched its redesigned
website using the UU2014 theme. We thought you might want to add it to your
list of UU churches using the theme.

You'll find the site at http://uuchurch.net.

—
Reply to this email directly or view it on GitHub
https://github.com/dflippo/UU2014/issues/84.

**Comment by YourErik** [comment]
Thank you for sharing. Yes the theme is user friendly, responsive and beautiful. How did you change the logo after the title? because in customization there is no option to add our own logo. I will use the UU 2014 platform not for the church. Hoping for the quick reply. Once again, Thank you so much.

YourErik

**Comment by SScott-UUCC** [comment]
Not sure what you’re asking. We did not change the logo. We put our logo at the top of the sidebar.

There is an option in Appearance>Customize>Display and Hide Features that allows you to turn off the stock graphic images.

Substituting a different image probably would require creating a child theme with the appropriate code.

Steve Scott

Scott Law Firm, P.C.

201 Westwood Ave.

Columbia, MO 65203-2871

Phone: 573-442-7268

Fax: 573-443-1676

 mailto:sscott@scottlawfirm.com sscott@scottlawfirm.com

**Comment by YourErik** [comment]
Sorry! I mean how I am going replace the default logo with my own logo. OK! creating a child theme would be the solution. Thanks for the quick response.

**Comment by YourErik** [comment]
Hi IgnitionMetalArtDesign, How did you change the default logo UU 2014? Did you made a child theme?

**Comment by dflippo** [comment]
Changing the logo is the first topic on the FAQ:
http://uuwp.org/category/news/faq-and-tips/
