### ISSUE TITLE
Audio files do not upload in the media manager

### ISSUE THREAD

**Issue by hdvtwin** [dflippo/UU2014#85]
Do I have to add an audio plugin to put upload audio files linked in my site?  Previously I just uploaded in the media manager and linked to a file.  Now the audio mp3 files will not upload.  I have compressed them so they are not too big.  Just changed about a month ago with the new uu-2014?  I can upload picture files but no audio.

**Comment by dflippo** [comment]
Sorry, your WordPress theme does not control anything related to mp3 files.
