### ISSUE TITLE
Media file size

### ISSUE THREAD

**Issue by kmkelsey** [dflippo/UU2014#86]
Is it possible to increase the file upload size beyond 1 MB?
Thank you.

**Comment by dflippo** [comment]
Sorry I didn't get back to you more promptly.  However, the upload size is not controlled by your WordPress theme.  That is controlled by PHP and the steps to change it vary for different web hosting companies.  If you do have the ability to configure your PHP settings, the entries you would want in your PHP.ini file:  

```
upload_max_filesize = 32M
post_max_size = 32M
```

These would increase the upload limit to 32 MB.  I suggest looking at the FAQ, Wiki, or forum for your web hosting company for how to increase the upload size limit.

**Comment by kmkelsey** [comment]
Hello Dan,

I thought you were the web hosting company!  We're using the free uuwp
site. starrkingfellowship.uuwp.org. Please help me understand.

**Comment by dflippo** [comment]
Oh, sorry about that, if so, you are absolutely correct.  I thought I had it set to 100 MB but I'll check again.

**Comment by dflippo** [comment]
I checked and both PHP settings are set to "100M".  However, I forgot needed to tell WordPress to use the same limit.  You should be able to upload files up to 100M now.

**Comment by kmkelsey** [comment]
Thank you. I can see the new limit has been set. Could you also tell me how
to set a password on the entire site?
