### ISSUE TITLE
adding my own image in the footer widget

### ISSUE THREAD

**Issue by hdvtwin** [dflippo/UU2014#87]
trying to add my own image in the footer widget?

<script> document.getElementById("site-title-image").src = "(my own web address here)/wp-content/themes/uu-2014/images/(myown image name here).png"; </script>

Your script doesn't seem to work in the footer widget content area.  What am I doing wrong?

**Comment by dflippo** [comment]
You can change your footer by including CSS in a text on your page to change the image.

```
<style>
.site-footer {
    background-image: url(http://hostname/folders/image.png);
}
</style>
```
