### ISSUE TITLE
Archives and Categories appearing on my left menu bar

### ISSUE THREAD

**Issue by RickDlott** [dflippo/UU2014#88]
Hi folks.  On our member only site I was doing some editing and found that the words Archives and Categories in a large font and I can't figure out how to disable this. 
<img width="1141" alt="screenshot 2015-11-08 20 27 36" src="https://cloud.githubusercontent.com/assets/15723449/11025944/4867c796-8657-11e5-9b0e-cf252e128709.png">

I'm not super code savvy - so would appreciate any help. 

Thanks
Rick

**Comment by dflippo** [comment]
It is discussed in other posts but they appear as a default when you haven't put anything in your sidebar widget area.  If you don't want anything but the menu on the left, you can add an empty text widget to your sidebar widget area.
